### PR TITLE
Fix issue 89

### PR DESCRIPTION
**Pull request by mhrobinson**
Fix missing nil check in vrouter.AddEndpoint

Signed-off-by: Mike Robinson <mikerob@cisco.com>

### CODE REVIEW

**Comment by mhrobinson** [comment]
It looks like there's something wrong with the automation environment; it can't find vagrant:

```text
vagrant box update
make: vagrant: Command not found
Makefile:9: recipe for target 'update' failed
make: *** [update] Error 127
Build step 'Execute shell' marked build as failure
```

**Comment by unclejack** [comment]
@mhrobinson: Thank you for letting us know. It's running now.

**Comment by jojimt** [comment]
LGTM. Thanks for taking care of this @mhrobinson

**Comment by mhrobinson** [comment]
Thanks @unclejack for fixing the env and @jojimt for merging it.

**Pull request merged**
