### PR TITLE
Makefile: add missing packages to check

### PR DESCRIPTION
**Pull request by unclejack**
This PR makes a change to ensure we check all packages.

### CODE REVIEW

**Comment by unclejack** [comment]
We need to address this issue before we can merge this PR:
```
ovsSwitch/ovsSwitch.go:275: suspect or: sw.netType != "vxlan" || sw.netType != "vrouter"
ovsSwitch/ovsSwitch.go:314: suspect or: sw.netType != "vxlan" || sw.netType != "vrouter"
```

**Comment by abhinandanpb** [comment]
@unclejack lets skip ovsSwitch for now. We are using the package in netplugin and not in ofnet.However the reason this is kept was we need to eventually start using it here. Hence its being ignored.
 libpkt was a a testing utility we wrote and did get a chance to use it to test ofnet. We can skip building that for now as well.

**Comment by unclejack** [comment]
@abhinandanpb: This is more about the basic checks to ensure the code is OK, regardless of where it's being used.

**Comment by unclejack** [comment]
This PR is green now. I've added a commit to add missing .PHONY targets to the Makefile.

PTAL

**Comment by unclejack** [comment]
I'll merge this now. It doesn't make any changes to the code.

**Pull request merged**
